
name: compliance

on: [push]

jobs:
  h2spec:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prerequisuites 
      run: |
        sudo apt-get update -y
        sudo apt install -y libasan6
    - name: build haproxy
      run: |
        make -j3 CC=gcc DEBUG_CFLAGS="-g -fsanitize=address" LDFLAGS="-fsanitize=address -lasan" ERR=1 TARGET=linux-glibc USE_OPENSSL=1
    - name: start haproxy
      run: |
        export ASAN_OPTIONS="log_path=asan.log
        ./haproxy -f .github/h2spec.config -D
    - name: download h2spec
      run: |
        wget https://github.com/summerwind/h2spec/releases/download/v2.6.0/h2spec_linux_amd64.tar.gz
        tar xvf h2spec_linux_amd64.tar.gz
    - name: run h2spec
      run: |
        ./h2spec -Svtk -h 127.0.0.1 -p 8443
    - name: check for asan log
      run: |
        if ls asan.log* 1> /dev/null 2>&1; then
           cat asan.log*
           exit 1
        fi
